### PR TITLE
Modified the details view so that the image scales without distortion.

### PR DESCRIPTION
**Pull request by kenpritchard**

### CODE REVIEW

**Comment by JohnLeeroy** [comment]
Closes #48.

**Comment by JohnLeeroy** [comment]
Suggested solution doesn't seem to look pretty in some cases.  We should consider maybe scaling it so the shortest edge (width or height) fills 360dp.  

device-2017-02-01-230838
device-2017-02-01-230920

**Comment by ToxicBakery** [comment]
I'm fairly certain we do not need any display metric calls or similar. Just call `.centerInside()` after `.fit()` to scale to the view dimensions.

**Comment by kenpritchard** [comment]
I didn't realize centerInside() could be called without first calling resize(), so I've replaced that call with a call to fit(). Is there still a problem with some of the images? If so let me know which ones, thanks.

**Comment by ToxicBakery** [comment]
Fixed in #52

**Pull request closed without merging**
