### PR TITLE
Feature/add fab

### PR DESCRIPTION
**Pull request by JohnLeeroy**

### CODE REVIEW

**Comment by JohnLeeroy** [comment]
I really dislike how the fab blocks part of the adoptable pet's image so there's an issue to hide the fab when the user is just browsing and scrolling down.  If they scroll back up, the fab should animate back into view.  If they scroll down, the fab will animate out of view.

**Comment by ToxicBakery** [comment]
What does the fab let you do?

**Comment by JohnLeeroy** [comment]
It lets you report missing pets and found missing pets.  Should lead to a new activity with a form to fill out.  Design-wise, do you think it's appropriate?

**Comment by ToxicBakery** [comment]
Not really. The FAB should be the most common actionable thing the user can and would want to do. If a fab exists anywhere in the app it would likely be on each pets detail screen and would provide the appropriate instructions to begin the adoption process. Since you posted screenshots with three actions I do not think a FAB is appropriate in that situation as it becomes redundant.

**Comment by JohnLeeroy** [comment]
I agree that these actions aren't going to be the most common action for the context. I'll shelf this feature for now.

**Pull request closed without merging**
